# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 18:20
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_bleach.models
import model_utils.fields
import versatileimagefield.fields


class Migration(migrations.Migration):

    replaces = [('monitorings', '0001_initial'), ('monitorings', '0002_auto_20160414_0903'), ('monitorings', '0003_auto_20160415_0711'), ('monitorings', '0004_auto_20160416_2353')]

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=b'name', unique=True, verbose_name='Slug')),
                ('description', django_bleach.models.BleachField(verbose_name='Description')),
                ('active', models.BooleanField(default=False, verbose_name='Active status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('institutions', models.ManyToManyField(help_text='Specifies which institutions are covered by monitoring', to=b'institutions.Institution', verbose_name='Institution')),
                ('logo', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=b'', verbose_name='Logo')),
            ],
            options={
                'ordering': ['active', 'created'],
                'verbose_name': 'Monitoring',
                'verbose_name_plural': 'Monitorings',
            },
        ),
    ]
