# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorings', '0002_auto_20160414_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active status'),
        ),
    ]
