# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 23:53
from __future__ import unicode_literals

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorings', '0003_auto_20160415_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='description',
            field=django_bleach.models.BleachField(verbose_name='Description'),
        ),
    ]
