# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorings', '0004_auto_20160416_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='institutions',
            field=models.ManyToManyField(blank=True, help_text='Specifies which institutions are covered by monitoring', to='institutions.Institution', verbose_name='Institution'),
        ),
    ]
