# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorings', '0008_auto_20160509_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active status'),
        ),
    ]
