# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitorings', '0009_auto_20160509_0151'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monitoringinstitution',
            unique_together=set([('monitoring', 'institution')]),
        ),
    ]
