# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 11:20
from __future__ import unicode_literals

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorings', '0010_auto_20160510_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='instruction',
            field=django_bleach.models.BleachField(default=b'', verbose_name='Instruction'),
        ),
    ]
