# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20160501_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerbool',
            name='sheet',
        ),
        migrations.RemoveField(
            model_name='answerdate',
            name='sheet',
        ),
        migrations.RemoveField(
            model_name='answertext',
            name='sheet',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questions.Question', verbose_name='Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answerbool',
            name='answer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='questions.Answer', verbose_name='Sheet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answerdate',
            name='answer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='questions.Answer', verbose_name='Answer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answertext',
            name='answer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='questions.Answer', verbose_name='Answer'),
            preserve_default=False,
        ),
    ]
