# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20160502_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerchoice',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Choice', verbose_name='Value'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('question', 'sheet')]),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together=set([('question', 'key')]),
        ),
        migrations.AlterUniqueTogether(
            name='sheet',
            unique_together=set([('monitoring', 'user')]),
        ),
    ]
