# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20160502_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='key',
            field=models.CharField(max_length=50, verbose_name='Key'),
        ),
    ]
