# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20160502_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='value',
            field=models.CharField(default='', max_length=50, verbose_name='Value'),
            preserve_default=False,
        ),
    ]
