# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_condition_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='value',
            field=models.CharField(blank=True, max_length=50, verbose_name='Value'),
        ),
    ]
