# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_auto_20160501_1128'),
        ('questions', '0009_auto_20160503_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_point',
            field=models.IntegerField(default=250, verbose_name='Max point'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheet',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution', verbose_name='Institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheet',
            name='point',
            field=models.IntegerField(default=250, verbose_name='Point'),
            preserve_default=False,
        ),
    ]
