# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20160504_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='max_point',
        ),
    ]
