# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_question_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertext',
            name='value',
            field=models.CharField(blank=True, max_length=150, verbose_name='Value'),
        ),
    ]
