# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 09:41
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_auto_20160505_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='count',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
