# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_auto_20160505_0941'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sheet',
            unique_together=set([('monitoring', 'user', 'institution')]),
        ),
    ]
