# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 07:11
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_bleach.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitorings', '0003_auto_20160415_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=b'name', unique_with=[b'monitoring'], verbose_name='Slug')),
                ('content', django_bleach.models.BleachField()),
                ('ordering', models.SmallIntegerField(default=0, verbose_name='Ordering')),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitorings.Monitoring', verbose_name='Monitoring')),
            ],
            options={
                'ordering': ['ordering', 'created'],
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
    ]
