# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 08:36
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=django_bleach.models.BleachField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=b'title', unique_with=[b'monitoring'], verbose_name='Slug'),
        ),
    ]
