# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 23:53
from __future__ import unicode_literals

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_pages', '0002_auto_20160415_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=django_bleach.models.BleachField(blank=True, verbose_name='Content'),
        ),
    ]
