# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 07:50
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teryt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=b'name', unique=True, verbose_name='Slug')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('regon', models.CharField(blank=True, max_length=14, verbose_name='REGON')),
                ('krs', models.CharField(blank=True, max_length=11, verbose_name='KRS')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teryt.JST', verbose_name='Unit of administrative division')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
            },
        ),
    ]
