# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorings', '0003_auto_20160415_0711'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='monitorings',
            field=models.ManyToManyField(to='monitorings.Monitoring'),
        ),
    ]
