# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_auto_20160501_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='monitorings',
            field=models.ManyToManyField(blank=True, to='monitorings.Monitoring', verbose_name='Monitorings'),
        ),
    ]
