# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_auto_20160501_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='monitorings',
        ),
    ]
