# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorings', '0008_auto_20160509_0031'),
        ('institutions', '0005_remove_institution_monitorings'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='monitorings',
            field=models.ManyToManyField(blank=True, through='monitorings.MonitoringInstitution', to='monitorings.Monitoring', verbose_name='Monitorings'),
        ),
    ]
